version: '3.1'
services:
  stats-server:
    build: stats-server/service
    image: stats_image
    container_name: 'stats-server'
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stat

  stats-db:
    image: postgres:14-alpine
    container_name: 'stats-db'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=stat
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root

  ewm-service:
    build: ewm-service
    image: ewm_image
    container_name: 'ewm-server'
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - EWM_SERVER_URL=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/main

  ewm-db:
    image: postgres:14-alpine
    container_name: 'ewm-db'
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=main
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root